//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсач
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bet
    {
        public int RaceId { get; set; }
        public int ClientID { get; set; }
        public int HorseID { get; set; }
        public int BetSum { get; set; }
        public bool isOpen { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Race Race { get; set; }
    }
}
