//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсач
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RaceEntities : DbContext
    {
        public RaceEntities()
            : base("name=RaceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Bet> Bet { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Horse> Horse { get; set; }
        public virtual DbSet<Race> Race { get; set; }
        public virtual DbSet<RaceMembers> RaceMembers { get; set; }
        public virtual DbSet<Rider> Rider { get; set; }
    }
}
