//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсач
{
    using System;
    using System.Collections.Generic;
    
    public partial class RaceMembers
    {
        public int RaceId { get; set; }
        public int RiderID { get; set; }
        public int Place { get; set; }
    
        public virtual Race Race { get; set; }
        public virtual Rider Rider { get; set; }
    }
}
